eshu/models.py
import base64
from Crypto.PublicKey import RSA
from Crypto.Util.number import bytes_to_long, long_to_bytes
from sqlalchemy.orm import relationship
from . import db


class Activity:
    pass


class Interaction(Activity):
    pass


class Account(db.Model):
    __tablename__ = 'account'

    account_id = db.Column(db.BigInteger(), primary_key=True)
    username = db.Column(db.Unicode(), nullable=False)
    domain = db.Column(db.Unicode(), nullable=True)

    # keypair
    private_key = db.Column(db.Text(), nullable=False)
    public_key = db.Column(db.Text(), nullable=False)

    # websub/ostatus stuff, not yet implemented
    atom_url = db.Column(db.Unicode(), nullable=True)
    salmon_url = db.Column(db.Unicode(), nullable=True)
    websub_secret = db.Column(db.Unicode(), nullable=True)
    websub_hub_url = db.Column(db.Unicode(), nullable=True)
    websub_deadline_ts = db.Column(db.DateTime(True), nullable=True)

    # activitypub endpoints
    inbox_url = db.Column(db.Unicode(), nullable=True)
    shared_inbox_url = db.Column(db.Unicode(), nullable=True)
    outbox_url = db.Column(db.Unicode(), nullable=True)

    # attributes
    display_name = db.Column(db.Unicode(), nullable=True)
    biography = db.Column(db.Text(), nullable=True)
    website_url = db.Column(db.Unicode(), nullable=True)
    avatar_url = db.Column(db.Unicode(), nullable=True)
    header_url = db.Column(db.Unicode(), nullable=True)

    # metrics
    last_webfinger_ts = db.Column(db.DateTime(True), nullable=True)

    @property
    def is_local(self):
        return self.domain == None

    @property
    def magic_key(self):
        try:
            pkey = RSA.importKey(self.public_key)
        except ValueError:
            return None

        parts = [
            b'RSA',
            base64.urlsafe_b64encode(long_to_bytes(pkey.n)),
            base64.urlsafe_b64encode(long_to_bytes(pkey.e))
        ]
        return b'.'.join(parts)


class Attachment(db.Model):
    __tablename__ = 'attachment'

    attachment_id = db.Column(db.BigInteger(), primary_key=True)
    attachment_uuid = db.Column(db.Unicode(), unique=True, nullable=False)
    account_id = db.Column(db.BigInteger(), db.ForeignKey('account.account_id'))
    account = relationship("Account", cascade="all, delete-orphan")
    uri = db.Column(db.Unicode(), nullable=False)


class Conversation(db.Model):
    __tablename__ = 'conversation'

    conversation_id = db.Column(db.BigInteger(), primary_key=True)
    creation_ts = db.Column(db.DateTime(True), nullable=False)
    updated_ts = db.Column(db.DateTime(True), nullable=False)


class Follow(Interaction, db.Model):
    __tablename__ = 'follow'
    __parent_verb__ = 'Follow'

    referent_id = db.Column(db.BigInteger(), primary_key=True)
    referent_ts = db.Column(db.DateTime(True), nullable=False)
    account_id = db.Column(db.BigInteger(), db.ForeignKey('account.account_id'), nullable=False)
    target_account_id = db.Column(db.BigInteger(), db.ForeignKey('account.account_id'), nullable=False)

    account = relationship("Account", foreign_keys=[account_id], cascade="all, delete-orphan",
                              back_populates="follows")
    target_account = relationship("Account", foreign_keys=[target_account_id], cascade="all, delete-orphan",
                              back_populates="followers")


class Block(Interaction, db.Model):
    __tablename__ = 'block'
    __parent_verb__ = 'Block'

    referent_id = db.Column(db.BigInteger(), primary_key=True)
    referent_ts = db.Column(db.DateTime(True), nullable=False)
    account_id = db.Column(db.BigInteger(), db.ForeignKey('account.account_id'), nullable=False)
    target_account_id = db.Column(db.BigInteger(), db.ForeignKey('account.account_id'), nullable=False)

    account = relationship("Account", foreign_keys=[account_id], cascade="all, delete-orphan",
                              back_populates="blocks")
    target_account = relationship("Account", foreign_keys=[target_account_id], cascade="all, delete-orphan",
                              back_populates="blocked_by")


class Note(Activity, db.Model):
    __tablename__ = 'note'
    __parent_verb__ = 'Create'
    __child_verb__ = 'Note'

    note_id = db.Column(db.BigInteger(), primary_key=True)
    note_uuid = db.Column(db.Unicode(), unique=True, nullable=False)
    note_ts = db.Column(db.DateTime(), nullable=False)

    account_id = db.Column(db.BigInteger(), db.ForeignKey('account.account_id'), nullable=False)
    summary = db.Column(db.Unicode(), nullable=True)
    content = db.Column(db.Text(), nullable=False)
    sensitive = db.Column(db.Boolean(), default=False, nullable=False)


class User(db.Model):
    __tablename__ = 'user'

    user_id = db.Column(db.BigInteger(), primary_key=True)
    account_id = db.Column(db.BigInteger(), db.ForeignKey('account.account_id'), nullable=False)
    passphrase = db.Column(db.Unicode(), nullable=False)
    email = db.Column(db.Unicode(), nullable=False)
    email_verified = db.Column(db.Boolean(), nullable=False, default=False)

    account = relationship("Account")

eshu/__init__.py
import asyncio
import aioredis
from sanic import Sanic
from gino.ext.sanic import Gino

from .aioredis_session import RedisSessionInterface
from sanic_jinja2 import SanicJinja2


app = Sanic()
app.config.from_envvar('ESHU_CONFIG')
app.static('/static', app.config.STATIC_DIR)

db = Gino()
db.init_app(app)


from . import locale
class EshuJinja(SanicJinja2):
    # XXX - implement me for real
    def fake_trans(self, text, *args, **kwargs):
        return locale.translate(text, locale.DefaultLocale)


jinja = EshuJinja(app, pkg_name='eshu')


class RedisPool:
    _pool = None

    async def get_redis_pool(self):
        if not self._pool:
            self._pool = await aioredis.create_redis_pool(app.config.REDIS_ENDPOINT)

        return self._pool


redispool = RedisPool()
session = RedisSessionInterface(redispool.get_redis_pool)


@app.middleware('request')
async def add_session_to_request(request):
    await session.open(request)


@app.middleware('response')
async def save_session(request, response):
    await session.save(request, response)


from . import models
from . import blueprints

eshu/blueprints/__init__.py
from .. import app
from .index import index_bp
from .user import user_bp


app.blueprint(index_bp)
app.blueprint(user_bp)

eshu/blueprints/index.py
from sanic import Blueprint
from .. import app, db, jinja


index_bp = Blueprint('index')


@index_bp.route('/')
async def index(request):
    return jinja.render('index.html', request)

eshu/blueprints/user.py
from sanic import Blueprint
from .. import app, db, jinja


user_bp = Blueprint('user')


@user_bp.route('/user/login')
async def login(request):
    return jinja.render('login.html', request)


@user_bp.route('/user/create')
async def create(request):
    return jinja.render('signup.html', request)

eshu/locale/__init__.py
# this is totally a stub
from .en import EnglishLocale


DefaultLocale = EnglishLocale


def translate(msgid, locale=DefaultLocale):
    return locale.get(msgid, 'No translation for %r' % msgid)

eshu/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title>{% block title %}{% endblock %} | Eshu</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.js" integrity="sha256-flVaeawsBV96vCHiLmXn03IRJym7+ZfcLVvUWONCas8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.css" integrity="sha256-wT6CFc7EKRuf7uyVfi+MQNHUzojuHN2pSw0YWFt2K5E=" crossorigin="anonymous">

    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

eshu/templates/signup.html
{% extends "base.html" %}

{% block title %}Create Account{% endblock %}

{% block head %}
{{ super() }}
	<style type="text/css">
		body {
			background-color: #DADADA;
		}

		body > .grid {
			height: 100%;
		}

		.image {
			margin-top: -100px;
		}

		.column {
			max-width: 450px;
		}
	</style>
{% endblock %}

{% block body %}

<div class="ui middle aligned center aligned grid">
	<div class="column">
		<form class="ui large form" method="POST">
			<div class="ui stacked segment">
				<div class="field">
					<div class="ui left icon input">
						<i class="user icon"></i>
						<input type="text" name="username" placeholder="{{ _("user.username") }}">
					</div>
				</div>
				<div class="field">
					<div class="ui left icon input">
						<i class="envelope icon"></i>
						<input type="text" name="email" placeholder="{{ _("user.email") }}">
					</div>
				</div>
				<div class="field">
					<div class="ui left icon input">
						<i class="lock icon"></i>
						<input type="password" name="password" placeholder="{{ _("user.password") }}">
					</div>
				</div>
				<button type="submit" class="ui fluid large teal submit button">{{ _("user.create") }}</button>
			</div>
		</form>

		<div class="ui message">
			{{ _("user.already_have_account") }} <a href="{{ url_for('user.login') }}">{{ _("user.login") }}</a>.
		</div>
	</div>
</div>

{% endblock %}
	